### ISSUE TITLE
Confused about reproducible results

### ISSUE THREAD

**Issue by wheltz** [lukasuz/Articulated-Point-NeRF#1]
Hello, thank you for your work. I ran the command you wrote in the readme about the jumpingjacks data set, but the results were terrible. However, I did not encounter any obstacles during the entire run, so I have no idea what caused the badness. very clear. I ran `python run.py --config configs/nerf/jumpingjacks.py --i_print 1000 --render_video --render_pcd`, 
`python run.py --config configs/nerf/jumpingjacks.py --i_print 1000 --visualise_canonical in sequence --render_pcd --render_only`, `python run.py --config configs/nerf/jumpingjacks.py --i_print 1000 --visualise_canonical --render_pcd --render_only --degree_threshold 30`,
`python run.py --config configs/nerf/jumpingjacks.py --i_print 1000 --repose_pcd --render_only --render_pcd --degree_threshold 30`.
Below are some results displayed( image in render_video_temporalpoints_last_time and canonical.pcd in pcds I can provide more if you need it)
![image](https://github.com/lukasuz/Articulated-Point-NeRF/assets/57028913/41952691-06d3-41d1-8169-fcd6252c992f)
![image](https://github.com/lukasuz/Articulated-Point-NeRF/assets/57028913/212c8af8-ad9b-41fd-a399-c20bc301841f)

**Comment by lukasuz** [comment]
Hey! That is indeed odd. It seems like something is going wrong with the first stage of the optimization as the point cloud is completely wrong. Potentially something is wrong with the dataset? A clean download might help. Otherwise visualising the camera poses might be good way to sanity-check. There is a script written by the DVGO people [here](https://github.com/sunset1995/DirectVoxGO/tree/main/tools) for this purpose. Then maybe try to train only the first part of the optimization by running this command:  `python run.py --config configs/nerf/jumpingjacks.py --i_print 1000 --render_video  --first_stage_only`. Let me know whether you could resolve the issue.

**Comment by wheltz** [comment]
Sorry for my late reply. I followed your prompts and ran `python run.py --config configs/nerf/jumpingjacks.py --i_print 1000 --render_video --first_stage_only`, and it turned out that it worked to some extent, but the performance was very bad ( I still haven't figured out why). 
![image](https://github.com/lukasuz/Articulated-Point-NeRF/assets/57028913/0d0e07ef-746c-4283-8469-42bc13ca173d)
![image](https://github.com/lukasuz/Articulated-Point-NeRF/assets/57028913/e0a91224-c6f8-44fe-9116-9e7043e165b4)

My jumpingjacks data set comes from the dropbox link shared by dnerf (https://www.dropbox.com/s/0bf6fl0ye2vz3vr/data.zip?e=1&dl=0).

**Comment by wheltz** [comment]
I've noticed that you might be quite busy and not logging into GitHub often. Could you let me know when you might have some time to address the issue I've raised? I'm more than willing to work around your schedule to get this resolved. Thanks!

**Comment by lukasuz** [comment]
Hey, thanks for your patience! There was indeed a bug, loading the wrong background color after cleaning up some parts of the code. I fixed it and just pushed the changes. Thanks for pointing it out! Let me know whether it works for you.

**Comment by wheltz** [comment]
Thanks a lot for updating the code! I'm gonna try it out and can't wait to see how it goes.

**Comment by wheltz** [comment]
The code update didn't fix the issue. However, running python run.py --config configs/nerf/jumpingjacks.py --i_print 1000 --render_video --render_pcd did give us something different this time.
![image](https://github.com/lukasuz/Articulated-Point-NeRF/assets/57028913/586890f9-845a-4d2d-80ca-348e91f6d632)

I also reran the first stage command and got the same results as before, which makes me think there might be an issue there. 
Plus, I double-checked the dnerf dataset against TiNeuVox and they match. But here's something: in the jumpingjacks test directory, the transforms.json still points to the dnerf author's path `/home/apumarola/datasets/nerf/nerf_synthetic_new/jumpingjacks`. No one really flagged it before, so I figured it wasn't a biggie, but thought I'd throw it out there in case it helps you out

**Comment by wheltz** [comment]
I tried out the wim dataset and got some pretty good results, actually. Looks like the problem might be with the dnerf dataset. I've checked over and over to make sure we got the right dataset, , so there’s probably a sneaky bug in how it's being handled that needs sorting out.

**Comment by lukasuz** [comment]
That is odd, after the changes I was able to get good results in the first stage, fixing the problems you were describing. Anyhow, thank you very much for the input! I will re-download the data and do a clean set up of the environment, to make sure there is nothing going wrong on my side. I will need a few days, I will probably get to it on Monday. If you still want to sanity-check nothing wrong is happening on your machine, you could try to run the [TiNeuVox](https://github.com/hustvl/TiNeuVox) repo on the dnerf data. It should be equivalent to first stage.

**Comment by wheltz** [comment]
Thanks so much for taking the time to help me out! I'll follow your advice and run TiNeuVox on the dnerf dataset.  Really, thanks a ton!

**Comment by wheltz** [comment]
I've tried training dnerf on TiNeuVox, and everything looks good, so there might be some unresolved bugs in the current version of your code on GitHub.

**Comment by lukasuz** [comment]
I did a clean set up of everything and it seems to be working fine. Are you sure that you retrained the first stage after I pushed the code last week? You would have to delete the weights and point cloud and skeleton .pcd manually. Looking at the image that you shared, it looks like only the background color changed in comparison to the first image the you posted in this thread.

**Comment by wheltz** [comment]
Oh, my apologies! It looks like it was indeed on me. After I followed your advice and manually removed the weights, point clouds, and skeletons, everything started working beautifully. Thanks a bunch for your help!

**Comment by lukasuz** [comment]
Happy to hear that it worked! I will close the issue then.
